### ISSUE TITLE
Feature suggestion: support to remap colors?

### ISSUE THREAD

**Issue by afharo** [8none1/idealLED#11]
Hi! I'd like to suggest a feature: support to remap colors.

I've got 2 LEDs strips that are controlled via iDealLED.

Thanks to this amazing integration, now I've got them in HA. However, I need to choose red color to get a yellowish/warm 2700k color.

Is there anyway that we could remap the colors somehow?

Thank you! Feel free to close this issue if this is not something you plan to do.

**Comment by 8none1** [comment]
Hi @afharo thanks for using the integration!

What you're describing sounds like your lights are using a (slightly) different protocol to my ones.  I think it would be better to spend some time understanding the new protocol and then adding support for it as a new model.

Could you share a link to where you got the lights, maybe I can find some near me or on Ali Express?

Also, if you fancy doing some detective work and have an Android phone, you can dump the Bluetooth logs where you open the app, change the colours, e.g. go red -> green -> blue -> red -> green -> blue a few times and then upload the btsnoop file to this issue.

This is what we did [here](https://github.com/8none1/idealLED/issues/10#issuecomment-2486126893) with success.

**Comment by afharo** [comment]
Hi @8none1

These are the ones I bought:
https://a.aliexpress.com/_Euuibzb

I bought the 10m and 20m versions.

TBH, even through the app, the color is not well mapped.

That's why I was hoping I could _remap_ them (when I choose Orange, make it more _redish_ so that the actual color is orange)

**Comment by 8none1** [comment]
Ahhhh, OK - I think I know what's going on here (but this is a guess...)

The long strings of lights require more power than a little USB port can provide, and so as you move further along the string the colours get more and more distorted from where they should be.

There isn't much you can do about this.  I don't think the controller would be happy with a higher voltage.

You can try to lower the brightness below 50%, that might at least get all the LEDs the same colour.

If you use some of the effects where only one or two LEDs are on at a time, do the colours look OK then?  If so, that supports the idea that it's a power supply problem.

Nevertheless, I have ordered a set of 10M lights and I will see what happens when the get here.

**Comment by afharo** [comment]
Your suspicion sounds sensible to me. I'll try out to lower the brightness and use half of the leds.

Although the same distorsion happens on both strips (the 10m and the 20m one): I actually grouped them in HA and control them as one.

**Comment by 8none1** [comment]
The new set of lights arrived and I have not been able to recreate this issue.  I got the 10M lights and setting the colour seems to provide a consistent colour along the whole length.

The colour reproduction isn't great, but it seems reasonable.  I don't really have any other suggestions here, perhaps your lights have a busted wire along the length somewhere?

Best solution is probably to work out what colour provides you the closest to what you want and use that.

**Comment by 8none1** [comment]
Oh, I have another idea.  These lights are restricted to use 5 bit colour instead of 8 bit because of the power problems.  That might be causing the poor colour reproduction too.  This you really shouldn't change because you could fuse the lights. 

https://github.com/8none1/idealLED/blob/e6257b6668375fdfd53a2ce9cebf57c82649700f/custom_components/ideal_led/idealled.py#L298

**Comment by afharo** [comment]
Oh! Thanks for looking into it anyways 🧡
